---
# https://github.com/Jguer/yay
- name: Cloning YAY
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/{{ user }}/yay
  
- name: Case insensitive password string match
  expect:
    command: makepkg -si
    chdir: /home/{{ user }}/yay
    responses:
      'sudo': "{{ user_password }}"
      'Y/n': "y"

- name: Clean artifacts
  file:
    state: absent
    path: "/home/{{ user }}/yay"
    force: yes