---
# - name: output disk and partition info
#  debug:
#    msg: "{{ item.value.partitions }}"
#  with_dict: "{{ hostvars[inventory_hostname].ansible_devices }}"
#  debug:
#    msg: "{{ hostvars[inventory_hostname].ansible_devices | community.general.json_query()  }}"
#msg: "{{ hostvars[inventory_hostname] | to_json }}"
#var: item
#loop: "{{ hostvars[inventory_hostname] | community.general.json_query('ansible_devices[*].partitions') }}"

#- name: Transfer the script
#  copy: src=../files/scripts/test.sh dest=/root mode=0777
#
#- name: Execute the script
#  expect:
#    command: /usr/bin/sh /root/test.sh
#    responses:
#      "Selec disk:": "/dev/sda"
#  register: outpout
#- debug: msg="{{outpout.stdout}}"
  - name: Output disks
    debug:
      var: (hostvars[inventory_hostname].ansible_devices | 
gather_disk_info