---
- name: Create {{ user }}
  user:
    name: "{{ user }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/zsh
    append: yes
    groups: "{{ user_groups | join(',') }}"
  