---
# https://github.com/Jguer/yay
- name: Cloning YAY
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "/home/{{ user }}/yay"
  
- name: Installing YAY
  expect:
    command: makepkg -si --noconfirm
    chdir: "/home/{{ user }}/yay"
    responses:
      'sudo': "{{ user_password }}"
    timeout: null

- name: Clean artifacts
  file:
    state: absent
    path: "/home/{{ user }}/yay"
    force: yes



