---
- name: Installing AUR packages
  expect:
    command: "yay -S --noconfirm --needed --cleanafter {{ item }}"
    responses:
      'sudo': "{{ user_password }}"
    timeout: null
  loop: "{{ aur_pkgs }}"